export const CATEGORY_REQUEST_STARTED = 'CATEGORY_REQUEST_STARTED';
export const CATEGORY_REQUEST_SUCCESS = 'CATEGORY_REQUEST_SUCCESS';
export const CATEGORY_REQUEST_FAILURE = 'CATEGORY_REQUEST_FAILURE';
