export const PRODUCT_REQUEST_STARTED = 'PRODUCT_REQUEST_STARTED';
export const PRODUCT_REQUEST_SUCCESS = 'PRODUCT_REQUEST_SUCCESS';
export const PRODUCT_REQUEST_FAILURE = 'PRODUCT_REQUEST_FAILURE';

export const ADD_PRODUCT_REQUEST_STARTED = 'ADD_PRODUCT_REQUEST_STARTED';
export const ADD_PRODUCT_REQUEST_SUCCESS = 'ADD_PRODUCT_REQUEST_SUCCESS';
export const ADD_PRODUCT_REQUEST_FAILURE = 'ADD_PRODUCT_REQUEST_FAILURE';
