export const SHIPPING_DETAILS_STARTED = 'SHIPPING_DETAILS_STARTED';
export const SHIPPING_DETAILS_SUCCESS = 'SHIPPING_DETAILS_SUCCESS';
export const SHIPPING_DETAILS_FAILURE = 'SHIPPING_DETAILS_FAILURE';
