export const SHIPPING_DETAILS_STARTED = 'SHIPPING_DETAILS_STARTED';
export const SHIPPING_DETAILS_SUCCESS = 'SHIPPING_DETAILS_SUCCESS';
export const SHIPPING_DETAILS_FAILURE = 'SHIPPING_DETAILS_FAILURE';

export const USER_SHIPPING_DETAILS_LIST_STARTED = 'USER_SHIPPING_DETAILS_LIST_STARTED';
export const USER_SHIPPING_DETAILS_LIST_SUCCESS = 'USER_SHIPPING_DETAILS_LIST_SUCCESS';
export const USER_SHIPPING_DETAILS_LIST_FAILURE = 'USER_SHIPPING_DETAILS_LIST_FAILURE';
